### ISSUE TITLE
TypeError on Import 

### ISSUE THREAD

**Issue by citizen00147** [PuruVJ/neodrag#121]
Hey there,

First off, love this library! I'm using the vanilla version and I'm getting a type error after importing: `Uncaught TypeError: The specifier “@neodrag/vanilla” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`

I think it's an issue with the path. I solved this by changing `import { Draggable } from "@neodrag/vanilla";` to `import { Draggable } from "../node_modules/@neodrag/vanilla/dist/min/index.js";` Once I changed that my object became draggable!

I've included a few screenshots of my test project below.

![TypeError](https://user-images.githubusercontent.com/85201967/220362024-067d45c1-692e-4422-96bb-25e8016b6263.png)
![TypeErrorHTML](https://user-images.githubusercontent.com/85201967/220363934-f98b46a5-a033-4b18-8139-4fe891c9e8f9.png)
![TypeErrorJS](https://user-images.githubusercontent.com/85201967/220363944-52fdda1a-a9de-4eb0-aaee-5dc41db57960.png)

**Comment by PuruVJ** [comment]
What bundler are you using?

**Comment by citizen00147** [comment]
> What bundler are you using?

Ah, so that must be my issue then? I'm not using a bundler.

**Comment by PuruVJ** [comment]
Ah! Wait, then how are you importing `@neodrag/vanilla` directly without a bundler?

**Comment by stepanjakl** [comment]
Hello @PuruVJ,

I would like to expand on this issue and ask if you could release a UMD version of the library, thereby allowing access through CDNs such as [UNPKG](https://www.unpkg.com/browse/embla-carousel/embla-carousel.umd.js)?

**Comment by stepanjakl** [comment]
I came up with a seperate solution to generate the UMD file using the Rollup compiler. Possibly it could make us of the NX package as well. It's just a first shot for now.

```js
// neodrag/packages/vanilla/rollup.config.js

import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import terser from '@rollup/plugin-terser';

const config = {
	input: 'src/index.ts',
	output: {
		name: 'Draggable',
		format: 'umd',
		file: 'dist/index.js'
	},
	plugins: [ typescript(), commonjs(), resolve(), /* terser() */ ]
};

export default config;

```
```js
// package.json

"scripts": {
        ...
	"compile:umd": "rollup --config"
}
```

**Comment by PuruVJ** [comment]
Hey! Sorry for the late reply.

Regarding your problem, is there anything stopping you from using `import { Draggable } from 'https://unpkg.com/@neodrag/vanilla@2.0.3/dist/min/index.js'`?

**Comment by stepanjakl** [comment]
@PuruVJ I am embedding scripts directly on the page without a compiler. If I use the `import` statement on the client/browser side I get this error: `Uncaught SyntaxError: Cannot use import statement outside a module`

**Comment by PuruVJ** [comment]
Ah! I'll add a UMD in that case

**Comment by PuruVJ** [comment]
Fixed a while before
