### ISSUE TITLE
pointermove and pointerup events should be added to the document only after pointerdown

### ISSUE THREAD

**Issue by santiagopuentep** [PuruVJ/neodrag#126]
Right now the `pointerup` and `pointermove` events are added to the `document` and constantly active for every draggable object in screen. The `pointerup` and `pointerup` should be added only inside the `pointerdown` event, otherwise this is a big performance issue.

Even better, they can be added to the node directly and `node.setPointerCapture(event.pointerId);` can be called inside `pointerup` so that the browser points all events to the node. This has the added benefit that if the pointer ever goes outside the bounds of the draggable, the pointer won't trigger other element's hover events for example.

See this [link](https://javascript.info/pointer-events#pointer-capturing) for more info.

**Comment by PuruVJ** [comment]
> The pointerup and pointerup should be added only inside the pointerdown event, otherwise this is a big performance issue.
Could you run benchmarks on this? From my testing, it didn't seem to make any difference in performance, nor memory allocation. Also, each pointer* event first makes sure that it is happening in the target element with `if(!is_interacting) return`, so effectively, no code other than this is running most of the time. Also to be noted: I have added event delegation for v3, hence having all the 3 events available at all times is required

> Even better, they can be added to the node directly and node.setPointerCapture(event.pointerId); can be called inside pointerup so that the browser points all events to the node. This has the added benefit that if the pointer ever goes outside the bounds of the draggable, the pointer won't trigger other element's hover events for example.
Implemented this for neodrag v3
