### ISSUE TITLE
Stopping click to pass to child

### ISSUE THREAD

**Issue by Andrioden** [PuruVJ/neodrag#130]
Hi, is there any way to stop a drag from ending up as an click on the child element? As I see it, its not about stopping event propagation, because its a child in this case.

I cant think of another way than to temporarily (using `setTimeout`) disable the `childClickHandler` in `onDragEnd`.

``` html
<div v-draggable="..."> 
   <div @click="childClickHandler">
</div>
```

**Comment by houtan-rocky** [comment]
#159 Solving this issue
