### ISSUE TITLE
build error: "draggable" is imported from external module "@neodrag/svelte" but never used...

### ISSUE THREAD

**Issue by eranmiller** [PuruVJ/neodrag#140]
First, I'd like to thank you for your very useful library.

All functionality is as advertised, except I'm getting this build error, and I was hoping you could explain if my implementation is the cause. I've poured over the documentation numerous times and have tried various configurations, alas this is what I get every time I run a build.
**"draggable" is imported from external module "@neodrag/svelte" but never used**

I've create a SvelteLab example to view the error live.
https://www.sveltelab.dev/lt1xord50oasihe

While I have your attention: Svelte 5 is coming soon... do you have plans to update your very useful library?

Thank you and Happy New Year!

**Comment by cmjoseph07** [comment]
@PuruVJ 
I am getting this same error still as well for awhile now in my Svelte project. Additionally, the Sveltelab example above does seem to re-produce this error if you run `npm run build` on it.

**Comment by PuruVJ** [comment]
Ohh I just saw the issue. It's strange. 

Fortunately, it doesn't affect the final bundle or the runtime implementation, so you're good to go on that front. It's not a TypeScript error either way, as vite build doesn't perform typescript analysis. This is something on vite's end only

**Comment by eranmiller** [comment]
Thanks for the feedback.
