### ISSUE TITLE
ignoreMultitouch:true do not work

### ISSUE THREAD

**Issue by Andrioden** [PuruVJ/neodrag#144]
neodrag interfers with multitouch events like pinching. I tested the demo her: https://www.neodrag.dev/docs/vue#ignoreMultitouch and even that one i am able to move the box when using two fingers on my mobile.

Environment:
- Android 14
- Galaxy S23
- One UI 6.1
- Firefox and Chrome

**Comment by PuruVJ** [comment]
Released in 2.0.4

**Comment by Andrioden** [comment]
Cool, are you releasing it to npm: https://www.npmjs.com/package/@neodrag/vue ?

**Comment by PuruVJ** [comment]
Just found it didn’t get released, releasing now

**Comment by PuruVJ** [comment]
Should be out now

**Comment by Andrioden** [comment]
Thanks for the quick response. Its still two problems:
- It does not default to true as documented (i tested i)
- Even when i have true set, i am still not able to pinch zoom with my mobile. You can verify this by:
   - 1. opening this on your mobile: https://www.neodrag.dev/docs/vue#ignoreMultitouch
   - 2. Pinch zoom (two fingers pinch in and ount) the box itself, be precice where you put your fingers so they are inside the red box: Does not work
   - 3. Pinch zoom outside the box: Zooms whole page

**Comment by Andrioden** [comment]
Hi, did you see my comment @PuruVJ ? Do you prefer that I make another Issue?
