### ISSUE TITLE
Bug: onDragEnd report wrong (0,0) offset when clicking element with preset position

### ISSUE THREAD

**Issue by Andrioden** [PuruVJ/neodrag#164]
The problem is if the user clicks/taps the draggable object, it wrongly report as if it was moved to position 0,0, while infact it was left at its initial position.

My options
``` js
        dragOptions: function() {
            return {
                position: {
                    x: 7,
                    y: 0
                },
                onDragStart: this.dragStartEventHandler,
                onDragEnd: this.dragStopEventHandler,
                defaultClassDragging: "dragging",
                ignoreMultitouch: true // Should default to false, but the library has a bug https://github.com/PuruVJ/neodrag/issues/144
            }
        },
```

My stop handler
``` js
        dragStopEventHandler: async function(event) {
            console.log(event.currentNode.style.transform) // = translate3d(7px, 0px, 0px)
            console.log(event.offsetX, event.offsetY) // = 0,0
            // I would expect it to be 7,0
        },
```

Extra info
- I also have a delegated click handler attached to a child of the draggable, this click event fire after the dragStop

Using
- "@neodrag/vue": "2.0.4"
- "@pnotify/core": "5.2.0"

**Comment by Andrioden** [comment]
`Workaround`
``` js
        dragStopEventHandler: async function(event) {
            if (event.currentNode.style.transform !== `translate3d(${event.offsetX}px, ${event.offsetY}px, 0px)`) {
                console.log("bug detected, abort")
                return
            }
            // ...
        },
```

**Comment by Andrioden** [comment]
Seems to be solved by the default treshold `{ distance: 3, delay: 0 }`, maybe the issue solvable. Thou, if someone uses distance 0 the bug may rappear?

**Comment by PuruVJ** [comment]
Correct, distance 0 would trigger falsely, sadly at that point it cannot be differentiated from a flick, which is why rhe default of 3 is in place. If distance is set to 0 delay could be set to 30-40 to avoid this
