### ISSUE TITLE
Why does `addEventListener`  attach to not `node` but `window`?

### ISSUE THREAD

**Issue by studioTeaTwo** [PuruVJ/neodrag#170]
I am going to use it in the case of multiple nodes and the repetition of `node.append/node.remove`.
This can cause problems because `removeEventListener` can not properly find the corresponding Listeners, leaving Listeners referencing the removed Node.

Current core code is:
```js
	const listen = addEventListener;

	listen('pointerdown', drag_start, false);
	listen('pointerup', drag_end, false);
	listen('pointermove', drag, false);
```
I think it's better:
```js
	const listen = node.addEventListener;

	listen('pointerdown', drag_start, false);
	listen('pointerup', drag_end, false);
	listen('pointermove', drag, false);
```

**Comment by PuruVJ** [comment]
Closing this, let me know if it helped
