### ISSUE TITLE
Draggables should use position as their defaultPosition

### ISSUE THREAD

**Issue by davjhan** [PuruVJ/neodrag#32]
Hi, first of all, love this library.

[In this example](https://svelte.dev/repl/e1e707358b37467ba272891715878a1d?version=3.44.1)

Setting the value of x and y
```
<script>
	import {draggable} from 'svelte-drag'
	
	let x = 100;
	let y = 0;
</script>
```

Should intuitively set the box at x=100 on first render. It does not. I see that defaultPosition achieves this, but I think intuitively, the x and y I pass in should be the initial position, as these can be props exposed to its parent.

**Comment by PuruVJ** [comment]
Good catch, will fix this

**Comment by PuruVJ** [comment]
Fixed https://github.com/PuruVJ/svelte-drag/releases/tag/2.4.1

**Comment by davjhan** [comment]
Thank you!
