### ISSUE TITLE
broken link (svelte)

### ISSUE THREAD

**Issue by oneezy** [PuruVJ/neodrag#45]
https://github.com/PuruVJ/neodrag/blob/main/tree/main/packages/svelte#readme

**Comment by PuruVJ** [comment]
Can you tell where you found this?

**Comment by oneezy** [comment]
hey there sorry about that!, it's here: https://github.com/PuruVJ/neodrag

all 4 of these links are 404's

![image](https://user-images.githubusercontent.com/7369575/152653582-c25ccb57-83a9-45b5-8bc2-19313ca06283.png)

**Comment by PuruVJ** [comment]
Fixed
