### ISSUE TITLE
adjusting on window resize

### ISSUE THREAD

**Issue by braebo** [PuruVJ/neodrag#62]
Draggables don't seem to react to window resize events.

They can become lost outside of the boundary because of this.

Not sure if this is because of something I've done on my end though.

**Comment by PuruVJ** [comment]
I've thought about this, and not sure how I want to tackle this. If you take draggable outside the svelte REPL examples and leave them here, they stay there. That much is predictive.

But if you have set the bounds, and resize causes it to go out of the bounds, then that is a possible issue. Should work on that. Thanks for letting me know. Will be using resizeObserver for this

**Comment by patriciatiffany** [comment]
I had a similar problem, and I wanted to use drag to change the position *without* transform/translate. If we're able to do that, I could imagine using the left/top positioning properties to position it as a % of the parent.  (The draggable elements would be absolutely positioned on a parent that scales with the window size.)

@PuruVJ , would you be open to exposing a custom style function? Like the custom transform that currently exists.

**Comment by PuruVJ** [comment]
> I had a similar problem, and I wanted to use drag to change the position *without* transform/translate. If we're able to do that, I could imagine using the left/top positioning properties to position it as a % of the parent.  (The draggable elements would be absolutely positioned on a parent that scales with the window size.)
> 
> @PuruVJ , would you be open to exposing a custom style function? Like the custom transform that currently exists.

You can do that with custom transform. If you don't return anything, no styles will be applied. You can directly apply `rootNode.style.top ` in customTransform

**Comment by PuruVJ** [comment]
There's a [`recomputeBounds`](https://www.neodrag.dev/docs/svelte#recomputeBounds) property where you can tell it to recompute bounds on the different lifecycles
