### ISSUE TITLE
On bounds update call computeBounds function?

### ISSUE THREAD

**Issue by alexey13** [PuruVJ/neodrag#64]
Good day! Firstly, thanks for great lib.

Iam updating bounds in ondrag stage, but because you are calling calculation of computedBounds in ondragstart stage, updated bounds not working. Maybe we should recalculate computedBounds in update function?

**Comment by PuruVJ** [comment]
See https://github.com/PuruVJ/neodrag/pull/65#issuecomment-1313257069
