### ISSUE TITLE
Use CSS `translate` property instead of `transform`

### ISSUE THREAD

**Issue by alluvion-dev** [PuruVJ/neodrag#72]
### Task Description
Replace, or provide the option to use, the CSS **`translate`** property in place of the currently used **`transform`** property.

### CSS **`translate`** property 
> The **`translate`** CSS property allows you to specify translation transforms individually and independently of the transform property. This maps better to typical user interface usage, and saves having to remember the exact order of transform functions to specify in the `transform `value. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/translate)

**Comment by KevsRepos** [comment]
I second this idea. The main benefit is that we can apply more transformations to the element without destroying the drag&drop functionality. Although I already encountered the problem that when applying `rotate` for example, the correct functionality already breaks... But that's another issue.
