### ISSUE TITLE
Allow elements to be swapped with each other?

### ISSUE THREAD

**Issue by MrNaughtZero** [PuruVJ/neodrag#77]
Hi, I'm working on a new side project, and it involves having a grid of draggable elements. I'm using this library in React. The goal is to drag an element the element somewhere on the grid, when dropped, find the closest element to its position, and swap the elements around. I have looked at the "Position" option, but this doesn't allow to change the X,Y relative to the container.

Is it possible to have a swap option in this library, so we can easily swap elements?

**Comment by PuruVJ** [comment]
I think you are looking for something like  
https://github.com/isaacHagoel/svelte-dnd-action

Does this answer your question?

**Comment by MrNaughtZero** [comment]
> I think you are looking for something like https://github.com/isaacHagoel/svelte-dnd-action
> 
> Does this answer your question?

I've managed to do most of drag/swap with this library. I'm stuck on one last thing. when onDragEnd is called, the offsetX and offsetY is changed. If we force a re-render, offsetX and offsetY never reset to 0. Is there a way to reset it?

**Comment by Sauerbac** [comment]
can u share ur solution?

**Comment by PuruVJ** [comment]
Glad you figured it out 🔥

**Comment by ealbinu** [comment]
But.... how? 😵‍💫

**Comment by jca41** [comment]
Also would like to know 😅
